/**
 * Vitrine — AI-native e-shop (ITC 4949 Capstone)
 * Copyright (c) 2026 George Papasotiriou. All rights reserved.
 * Author: George Papasotiriou <g.papasotiriou@acg.edu>
 * Project started: 2026-09-12
 *
 * Specimen catalogue data used by the design specimen page.
 */

/**
 * Specimen catalogue — generated by scripts/fetch-specimen-images.mjs.
 * Do not edit by hand; rerun the script instead.
 *
 * Product photography and metadata: Amazon Berkeley Objects (ABO), licensed
 * CC BY-NC 4.0. Non-commercial use only, which is what this capstone is.
 * https://amazon-berkeley-objects.s3.amazonaws.com/index.html
 *
 * Prices are synthetic: ABO carries no prices, so each is derived
 * deterministically from the item id within a documented per-category band
 * (docs/PLAN.md Phase 3, step 2). They are plausible, not real.
 *
 * This stands in until Phase 3 imports the full catalogue into PostgreSQL.
 */

export type SpecimenProduct = {
  id: string;
  slug: string;
  title: string;
  brand: string;
  category: string;
  categoryLabel: string;
  colour: string | null;
  /** Integer cents, EUR. Money is never a float (CLAUDE.md). */
  priceCents: number;
  image: { src: string; width: number; height: number };
  /** A second angle, revealed on hover (docs/PLAN.md 4.4). */
  hoverImage: { src: string; width: number; height: number } | null;
};

export const ATTRIBUTION =
  "Product images from the Amazon Berkeley Objects dataset, CC BY-NC 4.0.";

export const SPECIMEN_CATALOG: SpecimenProduct[] = [
  {
    "id": "B072ZLCB3M",
    "slug": "bristol-natural-edge-black-metal-side-table-cb3m",
    "title": "Bristol Natural Edge Black Metal Side Table",
    "brand": "Rivet",
    "category": "tables",
    "categoryLabel": "Tables",
    "colour": "Brown",
    "priceCents": 52900,
    "image": {
      "src": "/products/b072zlcb3m.webp",
      "width": 1100,
      "height": 1100
    },
    "hoverImage": {
      "src": "/products/b072zlcb3m-b.webp",
      "width": 1100,
      "height": 1100
    }
  },
  {
    "id": "B07F2X8K62",
    "slug": "radford-modern-curved-arm-accent-chair-8k62",
    "title": "Radford Modern Curved Arm Accent Chair",
    "brand": "Ravenna Home",
    "category": "seating",
    "categoryLabel": "Seating",
    "colour": null,
    "priceCents": 44900,
    "image": {
      "src": "/products/b07f2x8k62.webp",
      "width": 1100,
      "height": 1100
    },
    "hoverImage": {
      "src": "/products/b07f2x8k62-b.webp",
      "width": 1100,
      "height": 1100
    }
  },
  {
    "id": "B07M6PHM8C",
    "slug": "classic-glass-semi-flush-mount-light-pendant-hm8c",
    "title": "Classic Glass Semi-flush Mount Light Pendant",
    "brand": "Ravenna Home",
    "category": "lighting",
    "categoryLabel": "Lighting",
    "colour": "Dark Bronze",
    "priceCents": 7900,
    "image": {
      "src": "/products/b07m6phm8c.webp",
      "width": 1000,
      "height": 1000
    },
    "hoverImage": {
      "src": "/products/b07m6phm8c-b.webp",
      "width": 1000,
      "height": 1000
    }
  },
  {
    "id": "B07DBFT2YG",
    "slug": "angela-modern-turned-leg-wood-shelf-storage-coffee-t2yg",
    "title": "Angela Modern Turned Leg Wood Shelf Storage Coffee",
    "brand": "Ravenna Home",
    "category": "tables",
    "categoryLabel": "Tables",
    "colour": "Grey",
    "priceCents": 60900,
    "image": {
      "src": "/products/b07dbft2yg.webp",
      "width": 1100,
      "height": 775
    },
    "hoverImage": {
      "src": "/products/b07dbft2yg-b.webp",
      "width": 1100,
      "height": 1100
    }
  },
  {
    "id": "B07G2H3L4L",
    "slug": "canova-3-seater-maxi-3l4l",
    "title": "Canova 3 Seater Maxi",
    "brand": "ROSSINI",
    "category": "seating",
    "categoryLabel": "Seating",
    "colour": "Grey",
    "priceCents": 137900,
    "image": {
      "src": "/products/b07g2h3l4l.webp",
      "width": 1100,
      "height": 825
    },
    "hoverImage": {
      "src": "/products/b07g2h3l4l-b.webp",
      "width": 1100,
      "height": 825
    }
  },
  {
    "id": "B073P3NK7T",
    "slug": "modern-crystal-glass-rectangle-table-desk-lamp-with-nk7t",
    "title": "Modern Crystal Glass Rectangle Table Desk Lamp With",
    "brand": "Stone & Beam",
    "category": "lighting",
    "categoryLabel": "Lighting",
    "colour": "Polished Nickel",
    "priceCents": 7900,
    "image": {
      "src": "/products/b073p3nk7t.webp",
      "width": 1100,
      "height": 1100
    },
    "hoverImage": {
      "src": "/products/b073p3nk7t-b.webp",
      "width": 1100,
      "height": 1100
    }
  },
  {
    "id": "B07DBHCKHY",
    "slug": "tufted-armless-english-roll-traditional-accent-chair-ckhy",
    "title": "Tufted Armless English Roll Traditional Accent Chair",
    "brand": "Ravenna Home",
    "category": "seating",
    "categoryLabel": "Seating",
    "colour": "Merlot",
    "priceCents": 49900,
    "image": {
      "src": "/products/b07dbhckhy.webp",
      "width": 1100,
      "height": 1100
    },
    "hoverImage": {
      "src": "/products/b07dbhckhy-b.webp",
      "width": 1100,
      "height": 1100
    }
  },
  {
    "id": "B07HKDSM1J",
    "slug": "dome-shaped-table-lamp-sm1j",
    "title": "Dome-Shaped Table Lamp",
    "brand": "Rivet",
    "category": "lighting",
    "categoryLabel": "Lighting",
    "colour": "Tan/Pink",
    "priceCents": 25900,
    "image": {
      "src": "/products/b07hkdsm1j.webp",
      "width": 1010,
      "height": 1010
    },
    "hoverImage": {
      "src": "/products/b07hkdsm1j-b.webp",
      "width": 1000,
      "height": 1000
    }
  },
  {
    "id": "B07HK85JKQ",
    "slug": "modern-wall-sconce-with-bulb-5jkq",
    "title": "Modern Wall Sconce with Bulb",
    "brand": "Rivet",
    "category": "lighting",
    "categoryLabel": "Lighting",
    "colour": "Satin Brass",
    "priceCents": 28900,
    "image": {
      "src": "/products/b07hk85jkq.webp",
      "width": 1010,
      "height": 1010
    },
    "hoverImage": {
      "src": "/products/b07hk85jkq-b.webp",
      "width": 1000,
      "height": 1000
    }
  },
  {
    "id": "B082VLYQWX",
    "slug": "westview-extra-deep-down-filled-leather-sofa-couch-yqwx",
    "title": "Westview Extra-Deep Down-Filled Leather Sofa Couch",
    "brand": "Stone & Beam",
    "category": "seating",
    "categoryLabel": "Seating",
    "colour": "Dark Grey",
    "priceCents": 125900,
    "image": {
      "src": "/products/b082vlyqwx.webp",
      "width": 1100,
      "height": 501
    },
    "hoverImage": {
      "src": "/products/b082vlyqwx-b.webp",
      "width": 1100,
      "height": 1100
    }
  },
  {
    "id": "B07L8DQQ4Q",
    "slug": "lotusville-vintage-pu-leather-qq4q",
    "title": "Lotusville Vintage PU Leather",
    "brand": "Phoenix Home",
    "category": "seating",
    "categoryLabel": "Seating",
    "colour": "Grey",
    "priceCents": 17900,
    "image": {
      "src": "/products/b07l8dqq4q.webp",
      "width": 1024,
      "height": 682
    },
    "hoverImage": {
      "src": "/products/b07l8dqq4q-b.webp",
      "width": 1024,
      "height": 682
    }
  },
  {
    "id": "B07P6JV16D",
    "slug": "emerly-modern-sofa-v16d",
    "title": "Emerly Modern Sofa",
    "brand": "Rivet",
    "category": "seating",
    "categoryLabel": "Seating",
    "colour": "Steel",
    "priceCents": 169900,
    "image": {
      "src": "/products/b07p6jv16d.webp",
      "width": 1100,
      "height": 860
    },
    "hoverImage": {
      "src": "/products/b07p6jv16d-b.webp",
      "width": 1100,
      "height": 1100
    }
  },
  {
    "id": "B075YP4WVQ",
    "slug": "sophia-modern-swivel-kitchen-bar-stool-4wvq",
    "title": "Sophia Modern Swivel Kitchen Bar Stool",
    "brand": "Stone & Beam",
    "category": "seating",
    "categoryLabel": "Seating",
    "colour": "Merlot",
    "priceCents": 18900,
    "image": {
      "src": "/products/b075yp4wvq.webp",
      "width": 1100,
      "height": 1100
    },
    "hoverImage": {
      "src": "/products/b075yp4wvq-b.webp",
      "width": 683,
      "height": 1100
    }
  },
  {
    "id": "B07DT4GYTD",
    "slug": "modern-farmhouse-indoor-wall-sconce-with-led-gytd",
    "title": "Modern Farmhouse Indoor Wall Sconce With LED",
    "brand": "Stone & Beam",
    "category": "lighting",
    "categoryLabel": "Lighting",
    "colour": "Bronze",
    "priceCents": 11900,
    "image": {
      "src": "/products/b07dt4gytd.webp",
      "width": 1000,
      "height": 1000
    },
    "hoverImage": {
      "src": "/products/b07dt4gytd-b.webp",
      "width": 1000,
      "height": 1000
    }
  },
  {
    "id": "B07B4SC2KW",
    "slug": "vintage-bathroom-vanity-fixture-with-4-light-bulbs-c2kw",
    "title": "Vintage Bathroom Vanity Fixture With 4 Light Bulbs",
    "brand": "Stone & Beam",
    "category": "lighting",
    "categoryLabel": "Lighting",
    "colour": "Chrome",
    "priceCents": 17900,
    "image": {
      "src": "/products/b07b4sc2kw.webp",
      "width": 1100,
      "height": 1100
    },
    "hoverImage": {
      "src": "/products/b07b4sc2kw-b.webp",
      "width": 1100,
      "height": 1100
    }
  },
  {
    "id": "B07SJ75Y1M",
    "slug": "hayes-classic-fixed-solid-wood-dining-table-5y1m",
    "title": "Hayes Classic Fixed Solid Wood Dining Table",
    "brand": "Alkove",
    "category": "tables",
    "categoryLabel": "Tables",
    "colour": "Wild Oak",
    "priceCents": 40900,
    "image": {
      "src": "/products/b07sj75y1m.webp",
      "width": 1100,
      "height": 1100
    },
    "hoverImage": {
      "src": "/products/b07sj75y1m-b.webp",
      "width": 1024,
      "height": 683
    }
  },
  {
    "id": "B001BQ1Q9G",
    "slug": "pinzon-kinzie-leather-dining-chair-1q9g",
    "title": "Pinzon Kinzie Leather Dining Chair",
    "brand": "Pinzon by Amazon",
    "category": "seating",
    "categoryLabel": "Seating",
    "colour": "Cream",
    "priceCents": 51900,
    "image": {
      "src": "/products/b001bq1q9g.webp",
      "width": 767,
      "height": 1100
    },
    "hoverImage": null
  },
  {
    "id": "B07MM5H3HX",
    "slug": "classic-plank-top-console-table-with-large-drawer-h3hx",
    "title": "Classic Plank-Top Console Table with Large Drawer",
    "brand": "Ravenna Home",
    "category": "tables",
    "categoryLabel": "Tables",
    "colour": null,
    "priceCents": 11900,
    "image": {
      "src": "/products/b07mm5h3hx.webp",
      "width": 1100,
      "height": 871
    },
    "hoverImage": {
      "src": "/products/b07mm5h3hx-b.webp",
      "width": 1100,
      "height": 1100
    }
  },
  {
    "id": "B07MBFD87N",
    "slug": "faux-wood-table-lamp-d87n",
    "title": "Faux Wood Table Lamp",
    "brand": "Ravenna Home",
    "category": "lighting",
    "categoryLabel": "Lighting",
    "colour": "White",
    "priceCents": 9400,
    "image": {
      "src": "/products/b07mbfd87n.webp",
      "width": 1000,
      "height": 1000
    },
    "hoverImage": {
      "src": "/products/b07mbfd87n-b.webp",
      "width": 1000,
      "height": 1000
    }
  },
  {
    "id": "B07DBCG1Q2",
    "slug": "glass-stacked-ball-living-room-floor-lamp-with-led-g1q2",
    "title": "Glass Stacked Ball Living Room Floor Lamp with LED",
    "brand": "Ravenna Home",
    "category": "lighting",
    "categoryLabel": "Lighting",
    "colour": "Dark Bronze",
    "priceCents": 6900,
    "image": {
      "src": "/products/b07dbcg1q2.webp",
      "width": 1010,
      "height": 1010
    },
    "hoverImage": {
      "src": "/products/b07dbcg1q2-b.webp",
      "width": 1100,
      "height": 1100
    }
  },
  {
    "id": "B07B4Z9PWF",
    "slug": "stone-beam-rivet-cylinder-lamp-table-9pwf",
    "title": "Stone & Beam - Rivet Cylinder Lamp - Table",
    "brand": "Rivet",
    "category": "lighting",
    "categoryLabel": "Lighting",
    "colour": "Paint+plating",
    "priceCents": 16900,
    "image": {
      "src": "/products/b07b4z9pwf.webp",
      "width": 1100,
      "height": 1100
    },
    "hoverImage": {
      "src": "/products/b07b4z9pwf-b.webp",
      "width": 1100,
      "height": 1100
    }
  },
  {
    "id": "B0825DC7JP",
    "slug": "mid-century-modern-single-light-marble-pendant-with-c7jp",
    "title": "Mid-Century Modern Single-Light Marble Pendant with",
    "brand": "Rivet",
    "category": "lighting",
    "categoryLabel": "Lighting",
    "colour": "White",
    "priceCents": 19900,
    "image": {
      "src": "/products/b0825dc7jp.webp",
      "width": 1000,
      "height": 1000
    },
    "hoverImage": {
      "src": "/products/b0825dc7jp-b.webp",
      "width": 1000,
      "height": 1000
    }
  },
  {
    "id": "B07DBDV3FH",
    "slug": "swing-arm-living-room-floor-lamp-with-led-light-v3fh",
    "title": "Swing Arm Living Room Floor Lamp With LED Light",
    "brand": "Ravenna Home",
    "category": "lighting",
    "categoryLabel": "Lighting",
    "colour": "Brushed Steel",
    "priceCents": 13900,
    "image": {
      "src": "/products/b07dbdv3fh.webp",
      "width": 1010,
      "height": 1010
    },
    "hoverImage": {
      "src": "/products/b07dbdv3fh-b.webp",
      "width": 1000,
      "height": 1000
    }
  },
  {
    "id": "B07MBFDJQ3",
    "slug": "textured-ceramic-base-table-lamp-with-led-light-bulb-djq3",
    "title": "Textured Ceramic Base Table Lamp with LED Light Bulb",
    "brand": "Ravenna Home",
    "category": "lighting",
    "categoryLabel": "Lighting",
    "colour": "Silver",
    "priceCents": 23900,
    "image": {
      "src": "/products/b07mbfdjq3.webp",
      "width": 1000,
      "height": 1000
    },
    "hoverImage": {
      "src": "/products/b07mbfdjq3-b.webp",
      "width": 1000,
      "height": 1000
    }
  },
  {
    "id": "B07F2HNX7W",
    "slug": "luna-rustic-wood-stool-nx7w",
    "title": "Luna Rustic Wood Stool",
    "brand": "Ravenna Home",
    "category": "seating",
    "categoryLabel": "Seating",
    "colour": null,
    "priceCents": 19900,
    "image": {
      "src": "/products/b07f2hnx7w.webp",
      "width": 1100,
      "height": 944
    },
    "hoverImage": {
      "src": "/products/b07f2hnx7w-b.webp",
      "width": 1100,
      "height": 1100
    }
  }
];
