-- Catalogue migration (docs/PLAN.md 2.4, Phase 3). Generated by drizzle-kit, reviewed by hand.
--
-- categories, brands, products, product_variants, product_media.
--
-- Money is integer cents with a currency code, guarded by CHECK constraints.
-- search_tsv is a generated column over search text the application folds on
-- write (lower case, accents removed, final sigma as sigma), indexed with both
-- the english and greek text search configurations. Indexes: GIN on search_tsv,
-- GIN trigram on search_title (fuzzy retrieval), GIN on colour and material
-- arrays (filters), HNSW cosine on both embedding columns (semantic retrieval).
-- The embedding columns stay NULL until the embedding job fills them.

CREATE TYPE "public"."media_kind" AS ENUM('image', 'spin', 'model', 'video');--> statement-breakpoint
CREATE TYPE "public"."product_source" AS ENUM('abo', 'capsule');--> statement-breakpoint
CREATE TYPE "public"."product_status" AS ENUM('draft', 'active', 'archived');--> statement-breakpoint
CREATE TYPE "public"."translation_status" AS ENUM('none', 'machine', 'reviewed');--> statement-breakpoint
CREATE TABLE "brands" (
	"id" uuid PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" uuid PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"parent_id" uuid,
	"name_en" text NOT NULL,
	"name_el" text NOT NULL,
	"description_en" text,
	"description_el" text,
	"position" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "product_media" (
	"id" uuid PRIMARY KEY NOT NULL,
	"product_id" uuid NOT NULL,
	"kind" "media_kind" NOT NULL,
	"src" text NOT NULL,
	"width" integer,
	"height" integer,
	"bytes" integer,
	"alt_en" text NOT NULL,
	"alt_el" text,
	"position" integer DEFAULT 0 NOT NULL,
	"image_embedding" vector(768),
	"white_ground" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "product_media_src_is_path" CHECK ("product_media"."src" LIKE '/%')
);
--> statement-breakpoint
CREATE TABLE "product_variants" (
	"id" uuid PRIMARY KEY NOT NULL,
	"product_id" uuid NOT NULL,
	"sku" text NOT NULL,
	"color_label" text,
	"size" text,
	"price_cents" integer,
	"stock" integer DEFAULT 0 NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "product_variants_stock_nonnegative" CHECK ("product_variants"."stock" >= 0),
	CONSTRAINT "product_variants_price_nonnegative" CHECK ("product_variants"."price_cents" IS NULL OR "product_variants"."price_cents" >= 0)
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" uuid PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"source" "product_source" NOT NULL,
	"source_id" text NOT NULL,
	"status" "product_status" DEFAULT 'active' NOT NULL,
	"category_id" uuid NOT NULL,
	"brand_id" uuid,
	"kind" text NOT NULL,
	"title_en" text NOT NULL,
	"title_el" text,
	"description_en" text,
	"description_el" text,
	"highlights_en" text[] DEFAULT '{}'::text[] NOT NULL,
	"highlights_el" text[],
	"translation" "translation_status" DEFAULT 'none' NOT NULL,
	"color_label" text,
	"colors" text[] DEFAULT '{}'::text[] NOT NULL,
	"materials" text[] DEFAULT '{}'::text[] NOT NULL,
	"attributes" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"dims_cm" jsonb,
	"weight_grams" integer,
	"price_cents" integer NOT NULL,
	"compare_at_cents" integer,
	"currency" char(3) DEFAULT 'EUR' NOT NULL,
	"rating_sum" integer DEFAULT 0 NOT NULL,
	"rating_count" integer DEFAULT 0 NOT NULL,
	"popularity" integer DEFAULT 0 NOT NULL,
	"license" text NOT NULL,
	"attribution" text NOT NULL,
	"search_title" text DEFAULT '' NOT NULL,
	"search_meta" text DEFAULT '' NOT NULL,
	"search_attributes" text DEFAULT '' NOT NULL,
	"search_description" text DEFAULT '' NOT NULL,
	"search_tsv" "tsvector" GENERATED ALWAYS AS (
          setweight(to_tsvector('english', "products"."search_title") || to_tsvector('greek', "products"."search_title"), 'A') ||
          setweight(to_tsvector('english', "products"."search_meta") || to_tsvector('greek', "products"."search_meta"), 'B') ||
          setweight(to_tsvector('english', "products"."search_attributes") || to_tsvector('greek', "products"."search_attributes"), 'C') ||
          setweight(to_tsvector('english', "products"."search_description") || to_tsvector('greek', "products"."search_description"), 'D')) STORED NOT NULL,
	"text_embedding" vector(768),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "products_price_nonnegative" CHECK ("products"."price_cents" >= 0),
	CONSTRAINT "products_compare_at_above_price" CHECK ("products"."compare_at_cents" IS NULL OR "products"."compare_at_cents" > "products"."price_cents"),
	CONSTRAINT "products_rating_counts_nonnegative" CHECK ("products"."rating_count" >= 0 AND "products"."rating_sum" >= 0),
	CONSTRAINT "products_popularity_nonnegative" CHECK ("products"."popularity" >= 0)
);
--> statement-breakpoint
ALTER TABLE "categories" ADD CONSTRAINT "categories_parent_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."categories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_media" ADD CONSTRAINT "product_media_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_variants" ADD CONSTRAINT "product_variants_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "brands_slug_key" ON "brands" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "categories_slug_key" ON "categories" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "categories_parent_idx" ON "categories" USING btree ("parent_id");--> statement-breakpoint
CREATE UNIQUE INDEX "product_media_position_key" ON "product_media" USING btree ("product_id","kind","position");--> statement-breakpoint
CREATE INDEX "product_media_image_embedding_idx" ON "product_media" USING hnsw ("image_embedding" vector_cosine_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "product_variants_sku_key" ON "product_variants" USING btree ("sku");--> statement-breakpoint
CREATE INDEX "product_variants_product_idx" ON "product_variants" USING btree ("product_id","position");--> statement-breakpoint
CREATE UNIQUE INDEX "products_slug_key" ON "products" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "products_source_key" ON "products" USING btree ("source","source_id");--> statement-breakpoint
CREATE INDEX "products_category_idx" ON "products" USING btree ("category_id","status");--> statement-breakpoint
CREATE INDEX "products_brand_idx" ON "products" USING btree ("brand_id");--> statement-breakpoint
CREATE INDEX "products_price_idx" ON "products" USING btree ("price_cents");--> statement-breakpoint
CREATE INDEX "products_colors_idx" ON "products" USING gin ("colors");--> statement-breakpoint
CREATE INDEX "products_materials_idx" ON "products" USING gin ("materials");--> statement-breakpoint
CREATE INDEX "products_search_tsv_idx" ON "products" USING gin ("search_tsv");--> statement-breakpoint
CREATE INDEX "products_search_title_trgm_idx" ON "products" USING gin ("search_title" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "products_text_embedding_idx" ON "products" USING hnsw ("text_embedding" vector_cosine_ops);