-- Taste Graph migration (docs/PLAN.md 2.4 and 2.6 A2, Phase 8). Generated by drizzle-kit, reviewed by hand.
--
-- interactions: consented shopper behaviour keyed by an anonymous id; synthetic
-- marks simulated sessions. item_neighbors: precomputed top-50 neighbour lists
-- per product and kind (behaviour, content, blend), rebuilt by a worker job; a
-- product is never its own neighbour. Both cascade when a product is deleted.

CREATE TYPE "public"."interaction_kind" AS ENUM('view', 'dwell', 'cart', 'purchase', 'wishlist', 'search_click', 'tot_choice');--> statement-breakpoint
CREATE TYPE "public"."neighbor_kind" AS ENUM('behavior', 'content', 'blend');--> statement-breakpoint
CREATE TABLE "interactions" (
	"id" uuid PRIMARY KEY NOT NULL,
	"actor_id" text NOT NULL,
	"session_id" text NOT NULL,
	"product_id" uuid NOT NULL,
	"kind" "interaction_kind" NOT NULL,
	"dwell_seconds" integer,
	"synthetic" boolean DEFAULT false NOT NULL,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "interactions_dwell_nonnegative" CHECK ("interactions"."dwell_seconds" IS NULL OR "interactions"."dwell_seconds" >= 0)
);
--> statement-breakpoint
CREATE TABLE "item_neighbors" (
	"product_id" uuid NOT NULL,
	"kind" "neighbor_kind" NOT NULL,
	"neighbor_id" uuid NOT NULL,
	"score" double precision NOT NULL,
	"rank" integer NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "item_neighbors_product_id_kind_neighbor_id_pk" PRIMARY KEY("product_id","kind","neighbor_id"),
	CONSTRAINT "item_neighbors_not_self" CHECK ("item_neighbors"."product_id" <> "item_neighbors"."neighbor_id")
);
--> statement-breakpoint
ALTER TABLE "interactions" ADD CONSTRAINT "interactions_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "item_neighbors" ADD CONSTRAINT "item_neighbors_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "item_neighbors" ADD CONSTRAINT "item_neighbors_neighbor_id_products_id_fk" FOREIGN KEY ("neighbor_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "interactions_actor_idx" ON "interactions" USING btree ("actor_id","occurred_at");--> statement-breakpoint
CREATE INDEX "interactions_session_idx" ON "interactions" USING btree ("session_id","occurred_at");--> statement-breakpoint
CREATE INDEX "interactions_product_idx" ON "interactions" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "interactions_occurred_idx" ON "interactions" USING btree ("occurred_at");--> statement-breakpoint
CREATE INDEX "item_neighbors_rank_idx" ON "item_neighbors" USING btree ("product_id","kind","rank");