-- VAT by delivery country (docs/adr/013). Generated by drizzle-kit, edited and reviewed by hand.
--
-- Adds the VAT rate (tenths of a percent) and the country it was charged for to
-- every order. Only adds columns and a check; nothing is dropped. The generated
-- statements added NOT NULL columns without a value, which fails on a table
-- that already has orders, so existing rows are filled first: every order placed
-- before this migration was priced for Greece at 24%. The defaults are then
-- removed, so new orders must always state their own rate and country.

ALTER TABLE "orders" ADD COLUMN "vat_rate_per_mille" integer NOT NULL DEFAULT 240;--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "vat_rate_per_mille" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "vat_country" char(2) NOT NULL DEFAULT 'GR';--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "vat_country" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_vat_rate_range" CHECK ("orders"."vat_rate_per_mille" BETWEEN 0 AND 300);
