-- Who acted on an order (docs/adr/016). Generated by drizzle-kit, reviewed by hand.
--
-- Adds the person behind an order event when they have an account: the staff
-- member who packed, shipped or refunded it, or the customer who cancelled it.
-- Nullable and additive; existing history rows keep their actor type only.
-- Deleting an account keeps its history rows (set null).

ALTER TABLE "order_events" ADD COLUMN "actor_user_id" uuid;--> statement-breakpoint
ALTER TABLE "order_events" ADD CONSTRAINT "order_events_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;