-- Running the shop (docs/adr/018). Generated by drizzle-kit, reviewed by hand.
--
-- Additive only: two new tables, one enum and one nullable column. Nothing is
-- rewritten or dropped. products.staff_edited_at starts null for every product,
-- so the catalogue sync behaves exactly as before until staff edit one.
-- search_events keeps no user, session or address; rows older than 90 days
-- are deleted by the application.

CREATE TYPE "public"."search_source" AS ENUM('page', 'api');--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" uuid PRIMARY KEY NOT NULL,
	"actor_user_id" uuid,
	"actor_email" text,
	"action" text NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" text NOT NULL,
	"changes" jsonb NOT NULL,
	"reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "search_events" (
	"id" uuid PRIMARY KEY NOT NULL,
	"query" text NOT NULL,
	"locale" text NOT NULL,
	"results" integer NOT NULL,
	"relaxed" boolean DEFAULT false NOT NULL,
	"corrected" boolean DEFAULT false NOT NULL,
	"took_ms" integer NOT NULL,
	"source" "search_source" NOT NULL,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "search_events_results_nonnegative" CHECK ("search_events"."results" >= 0)
);
--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "staff_edited_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_actor_user_id_users_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "audit_log_entity_idx" ON "audit_log" USING btree ("entity_type","entity_id","created_at");--> statement-breakpoint
CREATE INDEX "audit_log_created_idx" ON "audit_log" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "search_events_occurred_idx" ON "search_events" USING btree ("occurred_at");