-- AI usage, allowances and budgets (docs/adr/019). Generated by drizzle-kit, reviewed by hand.
--
-- Additive only: two new tables, nothing else touched. ai_usage holds one row
-- per AI call (feature, model, tokens or units, cost in millionths of a euro)
-- and no message text or personal data; ai_allowances holds each shopper's
-- turns and credits per UTC day.

CREATE TABLE "ai_allowances" (
	"actor_key" text NOT NULL,
	"day" date NOT NULL,
	"turns" integer DEFAULT 0 NOT NULL,
	"credits" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ai_allowances_actor_key_day_pk" PRIMARY KEY("actor_key","day"),
	CONSTRAINT "ai_allowances_nonnegative" CHECK ("ai_allowances"."turns" >= 0 AND "ai_allowances"."credits" >= 0)
);
--> statement-breakpoint
CREATE TABLE "ai_usage" (
	"id" uuid PRIMARY KEY NOT NULL,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"feature" text NOT NULL,
	"provider" text NOT NULL,
	"model" text NOT NULL,
	"surface" text NOT NULL,
	"actor_key" text,
	"input_tokens" integer DEFAULT 0 NOT NULL,
	"output_tokens" integer DEFAULT 0 NOT NULL,
	"units" double precision DEFAULT 0 NOT NULL,
	"cost_micros" bigint,
	CONSTRAINT "ai_usage_counts_nonnegative" CHECK ("ai_usage"."input_tokens" >= 0 AND "ai_usage"."output_tokens" >= 0 AND "ai_usage"."units" >= 0 AND ("ai_usage"."cost_micros" IS NULL OR "ai_usage"."cost_micros" >= 0))
);
--> statement-breakpoint
CREATE INDEX "ai_usage_occurred_idx" ON "ai_usage" USING btree ("occurred_at");--> statement-breakpoint
CREATE INDEX "ai_usage_feature_idx" ON "ai_usage" USING btree ("feature","occurred_at");