-- Price watches and stored reports (docs/adr/020). Generated by drizzle-kit, reviewed by hand.
--
-- Additive only: two new tables. A watch belongs to an account and a product and
-- goes when either does; a report row points at a file in the shop's storage.

CREATE TABLE "price_watches" (
	"id" uuid PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"product_id" uuid NOT NULL,
	"target_cents" integer NOT NULL,
	"locale" text DEFAULT 'en' NOT NULL,
	"notified_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "price_watches_target_positive" CHECK ("price_watches"."target_cents" > 0)
);
--> statement-breakpoint
CREATE TABLE "reports" (
	"id" uuid PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"period_start" date NOT NULL,
	"period_end" date NOT NULL,
	"storage_key" text NOT NULL,
	"bytes" integer DEFAULT 0 NOT NULL,
	"summary" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "price_watches" ADD CONSTRAINT "price_watches_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "price_watches" ADD CONSTRAINT "price_watches_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "price_watches_person_product_key" ON "price_watches" USING btree ("user_id","product_id");--> statement-breakpoint
CREATE INDEX "price_watches_product_idx" ON "price_watches" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "reports_kind_idx" ON "reports" USING btree ("kind","period_end");