-- The support desk (docs/adr/021). Generated by drizzle-kit, reviewed by hand.
--
-- Additive only: three new tables. A ticket keeps its account, order and agent
-- as references that become null if any of them goes, because the conversation
-- is a record of what was said; its messages go with the ticket.

CREATE TABLE "support_macros" (
	"id" uuid PRIMARY KEY NOT NULL,
	"key" text NOT NULL,
	"topic" text DEFAULT 'other' NOT NULL,
	"title_en" text NOT NULL,
	"title_el" text NOT NULL,
	"body_en" text NOT NULL,
	"body_el" text NOT NULL,
	"sort" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "support_messages" (
	"id" uuid PRIMARY KEY NOT NULL,
	"ticket_id" uuid NOT NULL,
	"author" text NOT NULL,
	"author_user_id" uuid,
	"body" text NOT NULL,
	"draft" boolean DEFAULT false NOT NULL,
	"internal" boolean DEFAULT false NOT NULL,
	"model" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "support_tickets" (
	"id" uuid PRIMARY KEY NOT NULL,
	"number" text NOT NULL,
	"subject" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"topic" text DEFAULT 'other' NOT NULL,
	"locale" text DEFAULT 'en' NOT NULL,
	"email" text NOT NULL,
	"name" text NOT NULL,
	"user_id" uuid,
	"order_id" uuid,
	"assigned_to" uuid,
	"first_reply_due_at" timestamp with time zone NOT NULL,
	"first_reply_at" timestamp with time zone,
	"last_customer_at" timestamp with time zone DEFAULT now() NOT NULL,
	"resolved_at" timestamp with time zone,
	"closed_at" timestamp with time zone,
	"csat_score" integer,
	"csat_comment" text,
	"csat_answered_at" timestamp with time zone,
	"access_token_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "support_tickets_csat_range" CHECK ("support_tickets"."csat_score" IS NULL OR ("support_tickets"."csat_score" >= 1 AND "support_tickets"."csat_score" <= 5))
);
--> statement-breakpoint
ALTER TABLE "support_messages" ADD CONSTRAINT "support_messages_ticket_id_support_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."support_tickets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "support_messages" ADD CONSTRAINT "support_messages_author_user_id_users_id_fk" FOREIGN KEY ("author_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "support_tickets" ADD CONSTRAINT "support_tickets_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "support_tickets" ADD CONSTRAINT "support_tickets_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "support_tickets" ADD CONSTRAINT "support_tickets_assigned_to_users_id_fk" FOREIGN KEY ("assigned_to") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "support_macros_key_key" ON "support_macros" USING btree ("key");--> statement-breakpoint
CREATE INDEX "support_macros_topic_idx" ON "support_macros" USING btree ("topic","sort");--> statement-breakpoint
CREATE INDEX "support_messages_ticket_idx" ON "support_messages" USING btree ("ticket_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "support_tickets_number_key" ON "support_tickets" USING btree ("number");--> statement-breakpoint
CREATE INDEX "support_tickets_queue_idx" ON "support_tickets" USING btree ("status","first_reply_due_at");--> statement-breakpoint
CREATE INDEX "support_tickets_user_idx" ON "support_tickets" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "support_tickets_email_idx" ON "support_tickets" USING btree ("email","created_at");