-- Photographs a shopper gave the shop, and the try-ons made from them (docs/adr/023).
-- Generated by drizzle-kit, reviewed by hand.
--
-- Additive only: two new tables. A photograph goes when its owner's account
-- goes, and a try-on goes with its photograph; both carry the day they expire,
-- which the photo-expiry job reads.

CREATE TABLE "try_ons" (
	"id" uuid PRIMARY KEY NOT NULL,
	"upload_id" uuid NOT NULL,
	"product_id" uuid,
	"variant_id" uuid,
	"actor_key" text NOT NULL,
	"status" text DEFAULT 'queued' NOT NULL,
	"provider" text NOT NULL,
	"model" text NOT NULL,
	"result_key" text,
	"failure_reason" text,
	"cost_micros" integer,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "uploads" (
	"id" uuid PRIMARY KEY NOT NULL,
	"kind" text NOT NULL,
	"user_id" uuid,
	"actor_key" text NOT NULL,
	"storage_key" text NOT NULL,
	"content_type" text NOT NULL,
	"bytes" integer DEFAULT 0 NOT NULL,
	"width" integer,
	"height" integer,
	"consent_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uploads_bytes_nonnegative" CHECK ("uploads"."bytes" >= 0)
);
--> statement-breakpoint
ALTER TABLE "try_ons" ADD CONSTRAINT "try_ons_upload_id_uploads_id_fk" FOREIGN KEY ("upload_id") REFERENCES "public"."uploads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "try_ons" ADD CONSTRAINT "try_ons_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "try_ons" ADD CONSTRAINT "try_ons_variant_id_product_variants_id_fk" FOREIGN KEY ("variant_id") REFERENCES "public"."product_variants"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "uploads" ADD CONSTRAINT "uploads_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "try_ons_actor_idx" ON "try_ons" USING btree ("actor_key","created_at");--> statement-breakpoint
CREATE INDEX "try_ons_upload_idx" ON "try_ons" USING btree ("upload_id");--> statement-breakpoint
CREATE INDEX "uploads_expiry_idx" ON "uploads" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "uploads_actor_idx" ON "uploads" USING btree ("actor_key","created_at");